spring:
    datasource: 
        url: jdbc:postgresql://localhost:5432/feedback
        username: postgres
        password: Magni064fg$
    
        hikari:
            connection-timeout: 10000
            maximum-pool-size: 3
        
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                format_sql: true

