server:
    port: ${PORT}

spring:
    datasource: 
        url: ${JDBC_DATABASE_URL}
        username: ${JDBC_DATABASE_USERNAME}
        password: ${JDBC_DATABASE_PASSWORD}
    
        hikari:
            connection-timeout: 10000
            maximum-pool-size: 3
        
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                format_sql: true

